import { test as base, expect } from "@playwright/test";
import { test } from "./fixtures";

// Visual regression baseline for Phase 5. New snapshots are generated by
// running `npx playwright test --update-snapshots` (use `make e2e-update`
// in CI's reference container only — never on a developer's local machine).

base.describe("Visual regression — login (4 states)", () => {
  base("login idle", async ({ page }) => {
    await page.goto("/login");
    await expect(page).toHaveScreenshot("login-idle.png");
  });

  base("login error", async ({ page }) => {
    await page.goto("/login?error=oauth_failed");
    await expect(page).toHaveScreenshot("login-error.png");
  });

  base("login rejection", async ({ page }) => {
    await page.goto("/login?rejection=1");
    await expect(page).toHaveScreenshot("login-rejection.png");
  });
});

test.describe("Visual regression — project list", () => {
  test("empty state", async ({ signedInPage: page }) => {
    await page.goto("/");
    await page.getByTestId("empty-projects").waitFor();
    await expect(page).toHaveScreenshot("projects-empty.png");
  });

  // Populated grid visual baseline pending: needs a deterministic fixture
  // (seeded slugs → seeded mini-board distribution). Re-enable once Phase 6
  // (`scripts/seed_dev.py`) lands a fixed cohort.
});
